let tracklist = [
	"1 Hour - Best Music for Relaxing-Studying Vol.1 Anime Edition",
	"1 Hour - Best Music for Relaxing-Studying Vol.2 Anime Edition",
	"1 Hour - Best Music for Relaxing-Studying Vol.3 Anime Edition",
	"5-toubun no Hanayome - ED",
	"5-toubun no Hanayome - OP",
	"5-toubun no Hanayome ∬ - ED",
	"5-toubun no Hanayome ∬ - OP",
	"86 Part 2 - OP",
	"Aho Girl - ED",
	"Aho Girl - OP",
	"Ajin - ED",
	"Ajin - OP",
	"Ajin 2nd Season - OP 01",
	"Ajin 2nd Season - OP 02",
	"Akame Ga Kill - ED 01",
	"Akame Ga Kill - ED 02",
	"Akame Ga Kill - OP 01",
	"Akame Ga Kill - OP 02",
	"Akebi-chan no Sailor-fuku - OP",
	"Aldnoah.Zero - ED 01",
	"Aldnoah.Zero - ED 02",
	"Aldnoah.Zero - OP",
	"Aldnoah.Zero 2nd Season - ED 01",
	"Aldnoah.Zero 2nd Season - ED 02",
	"Aldnoah.Zero 2nd Season - OP",
	"Amagi Brilliant Park - ED",
	"Amagi Brilliant Park - OP",
	"Angel Beats - ED 01",
	"Angel Beats - ED 02",
	"Angel Beats - ED 03",
	"Angel Beats - IS 01",
	"Angel Beats - IS 02",
	"Angel Beats - IS 03",
	"Angel Beats - IS 04",
	"Angel Beats - IS 05",
	"Angel Beats - OP 01",
	"Angel Beats - OP 02",
	"Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai - ED",
	"Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai - OP",
	"Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai. Movie - OP",
	"Another - OP",
	"Ansatsu Kyoushitsu - OP 01",
	"Ansatsu Kyoushitsu - OP 02",
	"Ansatsu Kyoushitsu 2nd Season - OP 01",
	"Ansatsu Kyoushitsu 2nd Season - OP 02",
	"Ansatsu Kyoushitsu 365-nichi no Jikan - ED",
	"Ao no Exorcist - ED 01",
	"Ao no Exorcist - ED 02",
	"Ao no Exorcist - OP 01",
	"Ao no Exorcist - OP 02",
	"Ao no Exorcist Kyoto Fujouou-hen - ED",
	"Ao no Exorcist Kyoto Fujouou-hen - OP",
	"B The Beginning - OP",
	"BTOOOM! - ED 01",
	"BTOOOM! - OP 01",
	"BTOOOM! - OP 02",
	"Bakemonogatari - ED",
	"Bakemonogatari - OP 01",
	"Bakemonogatari - OP 02",
	"Bakemonogatari - OP 03",
	"Bakemonogatari - OP 04",
	"Bakemonogatari - OP 05",
	"Ballroom e Youkoso - ED 01",
	"Ballroom e Youkoso - ED 02",
	"Ballroom e Youkoso - OP 01",
	"Ballroom e Youkoso - OP 02",
	"Beastars - ED",
	"Beastars - OP",
	"Beastars 2nd Season - ED",
	"Beastars 2nd Season - OP",
	"Beatless - ED 01",
	"Beatless - OP 01",
	"Berserk (2016) - OP",
	"Berserk (2017) - OP",
	"Black Clover - ED 01",
	"Black Clover - ED 02",
	"Black Clover - ED 03",
	"Black Clover - ED 04",
	"Black Clover - ED 05",
	"Black Clover - ED 06",
	"Black Clover - ED 07",
	"Black Clover - ED 08",
	"Black Clover - ED 09",
	"Black Clover - ED 10",
	"Black Clover - ED 11",
	"Black Clover - ED 12",
	"Black Clover - ED 13",
	"Black Clover - OP 01",
	"Black Clover - OP 02",
	"Black Clover - OP 03",
	"Black Clover - OP 04",
	"Black Clover - OP 05",
	"Black Clover - OP 06",
	"Black Clover - OP 07",
	"Black Clover - OP 08",
	"Black Clover - OP 09",
	"Black Clover - OP 10",
	"Black Clover - OP 11",
	"Black Clover - OP 12",
	"Black Clover - OP 13",
	"Bleach - ED 28",
	"Bleach - OP 01",
	"Bleach - OP 02",
	"Bleach - OP 03",
	"Bleach - OP 04",
	"Bleach - OP 05",
	"Bleach - OP 06",
	"Bleach - OP 07",
	"Bleach - OP 08",
	"Bleach - OP 09",
	"Bleach - OP 10",
	"Bleach - OP 11",
	"Bleach - OP 12",
	"Bleach - OP 13",
	"Bleach - OP 14",
	"Bleach - OP 15",
	"Bleach - OST 02 11",
	"Bleach - OST 03 17",
	"Bleach - Original Soundtrack 「Complete Album」",
	"Blend S - ED",
	"Blend S - OP",
	"Boku dake ga Inai Machi - ED",
	"Boku dake ga Inai Machi - OP",
	"Boku no Hero Academia - ED",
	"Boku no Hero Academia - OP",
	"Boku no Hero Academia - OST 01",
	"Boku no Hero Academia - OST 02",
	"Boku no Hero Academia - OST 10",
	"Boku no Hero Academia - OST 15",
	"Boku no Hero Academia - OST 16",
	"Boku no Hero Academia - OST 22",
	"Boku no Hero Academia - OST 29",
	"Boku no Hero Academia - OST 35",
	"Boku no Hero Academia - OST Original Soundtrack",
	"Boku no Hero Academia 2nd Season - ED 01",
	"Boku no Hero Academia 2nd Season - ED 02",
	"Boku no Hero Academia 2nd Season - OP 01 YT",
	"Boku no Hero Academia 2nd Season - OP 01",
	"Boku no Hero Academia 2nd Season - OP 02",
	"Boku no Hero Academia 3rd Season - ED 01",
	"Boku no Hero Academia 3rd Season - ED 02",
	"Boku no Hero Academia 3rd Season - OP 01",
	"Boku no Hero Academia 3rd Season - OP 02",
	"Boku no Hero Academia 4th Season - ED 01",
	"Boku no Hero Academia 4th Season - ED 01",
	"Boku no Hero Academia 4th Season - ED 02",
	"Boku no Hero Academia 4th Season - IS",
	"Boku no Hero Academia 4th Season - OP 01",
	"Boku no Hero Academia 4th Season - OP 02",
	"Boku no Hero Academia 5th Season - ED 01",
	"Boku no Hero Academia 5th Season - ED 02",
	"Boku no Hero Academia 5th Season - OP 01",
	"Boku no Hero Academia 5th Season - OP 02",
	"Bokutachi wa Benkyou ga Dekinai - ED",
	"Bokutachi wa Benkyou ga Dekinai - OP",
	"Bokutachi wa Benkyou ga Dekinai! - ED",
	"Boogiepop wa Warawanai (2019) - ED",
	"Boogiepop wa Warawanai (2019) - OP",
	"Boruto Naruto Next Generations - ED 01",
	"Boruto Naruto Next Generations - ED 02",
	"Boruto Naruto Next Generations - ED 03",
	"Boruto Naruto Next Generations - ED 04",
	"Boruto Naruto Next Generations - ED 05",
	"Boruto Naruto Next Generations - ED 06",
	"Boruto Naruto Next Generations - ED 07",
	"Boruto Naruto Next Generations - ED 08",
	"Boruto Naruto Next Generations - ED 10",
	"Boruto Naruto Next Generations - ED 19",
	"Boruto Naruto Next Generations - OP 01",
	"Boruto Naruto Next Generations - OP 02",
	"Boruto Naruto Next Generations - OP 04",
	"Boruto Naruto Next Generations - OP 09",
	"Boruto Naruto Next Generations - OP 10",
	"Boruto Naruto the Movie - ED",
	"Bungou Stray Dogs - ED",
	"Bungou Stray Dogs - OP",
	"Bungou Stray Dogs 2nd Season - ED",
	"Bungou Stray Dogs 2nd Season - OP",
	"Bungou Stray Dogs 3rd Season - ED",
	"Bungou Stray Dogs 3rd Season - OP",
	"Bungou Stray Dogs Dead Apple - ED",
	"Bungou Stray Dogs Dead Apple - OP",
	"Burn the Witch - ED",
	"Charlotte - ED 01",
	"Charlotte - ED 02",
	"Charlotte - ED 03",
	"Charlotte - ED 04",
	"Charlotte - OP",
	"Charlotte - OST 23",
	"Chuunibyou demo Koi ga Shitai! - ED",
	"Chuunibyou demo Koi ga Shitai! - OP",
	"Chuunibyou demo Koi ga Shitai! Ren - ED",
	"Chuunibyou demo Koi ga Shitai! Ren - OP",
	"Citrus - ED",
	"Citrus - OP",
	"Clannad - ED",
	"Clannad - OP",
	"Clannad After Story - ED",
	"Clannad After Story - OP",
	"Code Geass Fukkatsu no Lelouch - ED",
	"Code Geass Fukkatsu no Lelouch - OST 01",
	"Code Geass Fukkatsu no Lelouch - OST",
	"Code Geass Hangyaku no Lelouch - ED 01",
	"Code Geass Hangyaku no Lelouch - ED 02",
	"Code Geass Hangyaku no Lelouch - OP 01",
	"Code Geass Hangyaku no Lelouch - OP 02",
	"Code Geass Hangyaku no Lelouch R2 - ED 01",
	"Code Geass Hangyaku no Lelouch R2 - ED 02",
	"Code Geass Hangyaku no Lelouch R2 - OP 01",
	"Code Geass Hangyaku no Lelouch R2 - OP 02",
	"Dagashi Kashi - ED",
	"Dagashi Kashi - OP",
	"Dagashi Kashi 2 - ED",
	"Dagashi Kashi 2 - OP",
	"Danganronpa Kibou no Gakuen to Zetsubou no Koukousei The Animation - ED 01",
	"Danganronpa Kibou no Gakuen to Zetsubou no Koukousei The Animation - ED 02",
	"Danganronpa Kibou no Gakuen to Zetsubou no Koukousei The Animation - OP 01",
	"Danganronpa Kibou no Gakuen to Zetsubou no Koukousei The Animation - OP 02",
	"Danshi Koukousei no Nichijou - ED 01",
	"Danshi Koukousei no Nichijou - ED 02",
	"Danshi Koukousei no Nichijou - OP",
	"Darling in the FranXX - ED 01",
	"Darling in the FranXX - ED 02",
	"Darling in the FranXX - ED 03",
	"Darling in the FranXX - ED 04",
	"Darling in the FranXX - ED 05",
	"Darling in the FranXX - ED 06",
	"Darling in the FranXX - OP YT",
	"Darling in the FranXX - OP",
	"Deadman Wonderland - ED",
	"Deadman Wonderland - OP",
	"Death Note - ED 01",
	"Death Note - ED 02",
	"Death Note - OP 01",
	"Death Note - OP 02",
	"Death Parade - ED",
	"Death Parade - OP",
	"Deca-Dence - ED",
	"Deca-Dence - OP",
	"Domestic na Kanojo - OP",
	"Dororo - ED 01",
	"Dororo - OP 01",
	"Dororo - OP 02",
	"Dr. Stone - ED 01",
	"Dr. Stone - ED 02",
	"Dr. Stone - OP 01",
	"Dr. Stone - OP 02",
	"Dr. Stone Stone Wars - ED",
	"Dr. Stone Stone Wars - OP",
	"Dragon Ball Super - ED 01",
	"Dragon Ball Super - ED 02",
	"Dragon Ball Super - ED 10",
	"Dragon Ball Super - OP 01",
	"Dragon Ball Super - OP 02",
	"Dragon Ball Super Broly - ED",
	"Dragon Ball Z Battle of Gods - ED",
	"Dumbbell Nan Kilo Moteru - ED",
	"Dumbbell Nan Kilo Moteru - OP",
	"Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka - ED",
	"Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka - IS EP 06",
	"Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka - OP",
	"Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka II - ED",
	"Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka II - OP",
	"Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka Movie Orion no Ya - OST",
	"Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka OVA - ED",
	"Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka Sword Oratoria - ED",
	"Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka Sword Oratoria - OP",
	"Edens Zero - ED 02",
	"Edens Zero - OP 02",
	"Elfen Lied - OP",
	"Enen no Shouboutai - ED 01",
	"Enen no Shouboutai - ED 02",
	"Enen no Shouboutai - OP 01",
	"Enen no Shouboutai - OP 02",
	"Enen no Shouboutai Ni no Shou - ED 01",
	"Enen no Shouboutai Ni no Shou - ED 02",
	"Enen no Shouboutai Ni no Shou - OP 01",
	"Enen no Shouboutai Ni no Shou - OP 02",
	"Eromanga-sensei - ED",
	"Eromanga-sensei - OP",
	"Evangelion 3.0+1.0 Thrice Upon a Time - IS",
	"Fairy Tail - OP 01",
	"Fairy Tail Final Series - ED 01",
	"Fairy Tail Final Series - ED 02",
	"Fairy Tail Final Series - ED 03",
	"Fairy Tail Final Series - ED 04",
	"Fairy Tail Final Series - OP 01",
	"Fairy Tail Final Series - OP 02",
	"Fairy Tail Final Series - OP 03",
	"Fairy Tail Final Series - OP 04",
	"Fate Apocrypha - ED 01",
	"Fate Apocrypha - ED 02",
	"Fate Apocrypha - OP 01",
	"Fate Apocrypha - OP 02",
	"Fate Grand Order Zettai Majuu Sensen Babylonia - ED 02",
	"Fate Grand Order Zettai Majuu Sensen Babylonia - ED",
	"Fate Grand Order Zettai Majuu Sensen Babylonia - OP",
	"Fate Stay Night - OP",
	"Fate Stay Night Movie Heaven's Feel - I. Presage Flower - ED",
	"Fate Stay Night Movie Heaven's Feel - II. Lost Butterfly - ED",
	"Fate Stay Night Movie Heaven's Feel - III. Spring Song - ED",
	"Fate Stay Night Unlimited Blade Works - ED 01",
	"Fate Stay Night Unlimited Blade Works - ED 02",
	"Fate Stay Night Unlimited Blade Works - OP",
	"Fate Stay Night Unlimited Blade Works 2nd Season - ED",
	"Fate Stay Night Unlimited Blade Works 2nd Season - OP",
	"Fate Zero - ED",
	"Fate Zero - OP",
	"Fate Zero 2nd Season - ED 01",
	"Fate Zero 2nd Season - ED 02",
	"Fate Zero 2nd Season - OP",
	"Fullmetal Alchemist - OP 02",
	"Fullmetal Alchemist Brotherhood - ED 01",
	"Fullmetal Alchemist Brotherhood - ED 02",
	"Fullmetal Alchemist Brotherhood - ED 03",
	"Fullmetal Alchemist Brotherhood - ED 04",
	"Fullmetal Alchemist Brotherhood - ED 05",
	"Fullmetal Alchemist Brotherhood - OP 01",
	"Fullmetal Alchemist Brotherhood - OP 02",
	"Fullmetal Alchemist Brotherhood - OP 03",
	"Fullmetal Alchemist Brotherhood - OP 04",
	"Fullmetal Alchemist Brotherhood - OP 05",
	"Gamers! - ED 01",
	"Gamers! - ED 02",
	"Gamers! - OP",
	"Gate Jieitai Kanochi nite, Kaku Tatakaeri - ED ( Lelei Ver.)",
	"Gate Jieitai Kanochi nite, Kaku Tatakaeri - ED ( Rory Ver.)",
	"Gate Jieitai Kanochi nite, Kaku Tatakaeri - ED ( Tuka Ver.)",
	"Gate Jieitai Kanochi nite, Kaku Tatakaeri - ED",
	"Gate Jieitai Kanochi nite, Kaku Tatakaeri - OP",
	"Gate Jieitai Kanochi nite, Kaku Tatakaeri 2nd Season - ED ( Lelei Ver.)",
	"Gate Jieitai Kanochi nite, Kaku Tatakaeri 2nd Season - ED ( Rory Ver.)",
	"Gate Jieitai Kanochi nite, Kaku Tatakaeri 2nd Season - ED ( Tuka Ver.)",
	"Gate Jieitai Kanochi nite, Kaku Tatakaeri 2nd Season - ED",
	"Gate Jieitai Kanochi nite, Kaku Tatakaeri 2nd Season - OP",
	"Gintama' Enchousen - OP 03",
	"Goblin Slayer - ED 01",
	"Goblin Slayer - ED 02",
	"Goblin Slayer - ED 03",
	"Goblin Slayer - OP",
	"God Eater - OP",
	"Guilty Crown - ED 01",
	"Guilty Crown - ED 02",
	"Guilty Crown - OP 01",
	"Guilty Crown - OP 02",
	"Hai to Gensou no Grimgar - ED 01",
	"Hai to Gensou no Grimgar - ED 02",
	"Hai to Gensou no Grimgar - ED 03",
	"Hai to Gensou no Grimgar - OP",
	"Haikyuu!! - ED 01",
	"Haikyuu!! - ED 02",
	"Haikyuu!! - OP 01",
	"Haikyuu!! - OP 02",
	"Haikyuu!! Karasuno Koukou VS Shiratorizawa Gakuen Koukou - ED",
	"Haikyuu!! Karasuno Koukou VS Shiratorizawa Gakuen Koukou - OP",
	"Haikyuu!! Second Season - ED 01",
	"Haikyuu!! Second Season - ED 02",
	"Haikyuu!! Second Season - OP 01",
	"Haikyuu!! Second Season - OP 02",
	"Haikyuu!! To the Top - ED",
	"Haikyuu!! To the Top - OP",
	"Haikyuu!! To the Top 2nd Season - ED",
	"Haikyuu!! To the Top 2nd Season - OP",
	"Haiyore! Nyaruko-san - ED",
	"Haiyore! Nyaruko-san - OP",
	"Haiyore! Nyaruko-san W - ED 01",
	"Haiyore! Nyaruko-san W - ED 02",
	"Haiyore! Nyaruko-san W - ED 03",
	"Haiyore! Nyaruko-san W - ED 04",
	"Haiyore! Nyaruko-san W - ED 05",
	"Haiyore! Nyaruko-san W - ED 06",
	"Haiyore! Nyaruko-san W - OP",
	"Hanamonogatari - ED",
	"Hanamonogatari - OP",
	"Hataraku Maou-sama! - ED 01",
	"Hataraku Maou-sama! - ED 02",
	"Hataraku Maou-sama! - ED 03",
	"Hataraku Maou-sama! - OP",
	"Hataraku Saibou - ED",
	"Hentai Ouji to Warawanai Neko - ED",
	"Hentai Ouji to Warawanai Neko - OP",
	"Hidan no Aria AA - OP",
	"Hige wo Soru. Soshite Joshikousei wo Hirou. - ED",
	"Hige wo Soru. Soshite Joshikousei wo Hirou. - OP",
	"Himouto! Umaru-chan - ED",
	"Himouto! Umaru-chan - OP",
	"Himouto! Umaru-chan R - ED",
	"Himouto! Umaru-chan R - OP",
	"Hinamatsuri - ED 01",
	"Hinamatsuri - OP",
	"Hitoribocchi no Marumaru Seikatsu - ED 01",
	"Hitoribocchi no Marumaru Seikatsu - ED 02",
	"Hitoribocchi no Marumaru Seikatsu - OP",
	"Horimiya - ED",
	"Horimiya - OP",
	"Hunter X Hunter (2011) - ED 05",
	"Hunter X Hunter (2011) - OP",
	"Hyouka - ED 01",
	"Hyouka - ED 02",
	"Hyouka - OP 01",
	"Hyouka - OP 02",
	"Ijiranaide, Nagatoro-san - ED",
	"Ijiranaide, Nagatoro-san - OP",
	"Initial D First Stage - OST 09",
	"Initial D Fist Stage - OST 01",
	"Initial D Fourth Stage - OST 08",
	"Irozuku Sekai no Ashita kara - ED",
	"Irozuku Sekai no Ashita kara - OP",
	"Isekai Maou to Shoukan Shoujo no Dorei Majutsu - ED",
	"Isekai Maou to Shoukan Shoujo no Dorei Majutsu - OP",
	"Isekai Quartet - ED",
	"Isekai Quartet - OP",
	"Isekai Quartet 2 - ED",
	"Isekai Quartet 2 - OP",
	"Itai no wa Iya nano de Bougyoryoku ni Kyokufuri Shitai to Omoimasu. - ED",
	"Itai no wa Iya nano de Bougyoryoku ni Kyokufuri Shitai to Omoimasu. - OP",
	"Jahy-sama wa Kujikenai! - ED 01",
	"Jahy-sama wa Kujikenai! - ED 02",
	"Jahy-sama wa Kujikenai! - OP 01",
	"Jahy-sama wa Kujikenai! - OP 02",
	"Jaku-Chara Tomozaki-kun - ED",
	"Jaku-Chara Tomozaki-kun - OP",
	"Jinrui wa Suitai Shimashita - ED",
	"Jinrui wa Suitai Shimashita - OP",
	"JoJo no Kimyou na Bouken - ED",
	"JoJo no Kimyou na Bouken - OP 01",
	"JoJo no Kimyou na Bouken - OP 02",
	"JoJo no Kimyou na Bouken Diamond wa Kudakenai - ED",
	"JoJo no Kimyou na Bouken Diamond wa Kudakenai - OP 01",
	"JoJo no Kimyou na Bouken Diamond wa Kudakenai - OP 02",
	"JoJo no Kimyou na Bouken Diamond wa Kudakenai - OP 03",
	"JoJo no Kimyou na Bouken Ougon no Kaze - ED 01",
	"JoJo no Kimyou na Bouken Ougon no Kaze - ED 02",
	"JoJo no Kimyou na Bouken Ougon no Kaze - OP 01",
	"JoJo no Kimyou na Bouken Ougon no Kaze - OP 02",
	"JoJo no Kimyou na Bouken Stardust Crusaders - ED",
	"JoJo no Kimyou na Bouken Stardust Crusaders - OP",
	"JoJo no Kimyou na Bouken Stardust Crusaders 2nd Season - ED",
	"JoJo no Kimyou na Bouken Stardust Crusaders 2nd Season - OP",
	"Josee to Tora to Sakana-tachi - IS",
	"Josee to Tora to Sakana-tachi - Theme Song",
	"Joshiraku - ED",
	"Jujutsu Kaisen - ED 01",
	"Jujutsu Kaisen - ED 02",
	"Jujutsu Kaisen - OP 01",
	"Jujutsu Kaisen - OP 02",
	"Jujutsu Kaisen 0 Movie - ED",
	"Jujutsu Kaisen 0 Movie - OP",
	"K-On! - ED",
	"K-On! - OP",
	"K-On!! - ED 01",
	"K-On!! - ED 02",
	"K-On!! - OP 01",
	"K-On!! - OP 02",
	"K-On!! - OST 04",
	"Kaguya-sama wa Kokurasetai Tensai-tachi no Renai Zunousen - ED 01",
	"Kaguya-sama wa Kokurasetai Tensai-tachi no Renai Zunousen - ED 02",
	"Kaguya-sama wa Kokurasetai Tensai-tachi no Renai Zunousen - OP",
	"Kaguya-sama wa Kokurasetai Tensai-tachi no Renai Zunousen 2nd Season - ED",
	"Kaguya-sama wa Kokurasetai Tensai-tachi no Renai Zunousen 2nd Season - OP",
	"Kakegurui - ED",
	"Kakegurui - OP",
	"Kakegurui×× - ED",
	"Kakegurui×× - OP",
	"Kami no Tou - ED",
	"Kami no Tou - OP",
	"Kanojo mo Kanojo - ED",
	"Kanojo mo Kanojo - OP",
	"Kanojo, Okarishimasu - ED 01",
	"Kanojo, Okarishimasu - ED 02",
	"Kanojo, Okarishimasu - ED 03",
	"Kanojo, Okarishimasu - OP",
	"Karakai Jouzu no Takagi-san - ED 01",
	"Karakai Jouzu no Takagi-san - ED 02",
	"Karakai Jouzu no Takagi-san - ED 03",
	"Karakai Jouzu no Takagi-san - ED 04",
	"Karakai Jouzu no Takagi-san - OP",
	"Karakai Jouzu no Takagi-san 2 - ED 01",
	"Karakai Jouzu no Takagi-san 2 - ED 02",
	"Karakai Jouzu no Takagi-san 2 - ED 03",
	"Karakai Jouzu no Takagi-san 2 - ED 04",
	"Karakai Jouzu no Takagi-san 2 - OP",
	"Karakuri Circus - OP 02",
	"Kekkai Sensen & Beyond - ED",
	"Kekkai Sensen & Beyond - OP",
	"Kekkai Sensen - ED",
	"Kekkai Sensen - OP",
	"Kill La Kill - ED 01",
	"Kill La Kill - ED 02",
	"Kill La Kill - OP 01",
	"Kill La Kill - OP 02",
	"Kimetsu no Yaiba - ED",
	"Kimetsu no Yaiba - IS 19",
	"Kimetsu no Yaiba - OP",
	"Kimetsu no Yaiba Movie Mugen Ressha-hen- ED",
	"Kimetsu no Yaiba Mugen Ressha-hen - ED",
	"Kimetsu no Yaiba Mugen Ressha-hen - OP",
	"Kimetsu no Yaiba Yuukaku-hen - ED",
	"Kimi no Na wa. - OST 01",
	"Kimi no Na wa. - OST 08",
	"Kimi no Na wa. - OST 24",
	"Kimi no Na wa. - OST 26",
	"Kimi no Na wa. - OST 27",
	"Kimi no Suizo wo Tabetai - ED",
	"Kimi no Suizo wo Tabetai - OP",
	"Kiseijuu Sei no Kakuritsu - ED",
	"Kiseijuu Sei no Kakuritsu - OP",
	"Kishuku Gakkou no Juliet - ED",
	"Kishuku Gakkou no Juliet - OP",
	"Kizumonogatari - MAD",
	"Kobayashi-san Chi no Maid Dragon - ED",
	"Kobayashi-san Chi no Maid Dragon - OP",
	"Kobayashi-san Chi no Maid Dragon S - ED",
	"Kobayashi-san Chi no Maid Dragon S - OP",
	"Koe no Katachi - ED",
	"Koi wa Ameagari no You ni - ED",
	"Koi wa Ameagari no You ni - OP",
	"Kokoro Connect - ED 01",
	"Kokoro Connect - ED 02",
	"Kokoro Connect - ED 03",
	"Kokoro Connect - OP 01",
	"Kokoro Connect - OP 02",
	"Komi-san wa, Comyushou desu. - ED EP1",
	"Komi-san wa, Comyushou desu. - ED",
	"Komi-san wa, Comyushou desu. - OP",
	"Kono Subarashii Sekai ni Shukufuku wo! - ED ( Aqua Ver.)",
	"Kono Subarashii Sekai ni Shukufuku wo! - ED ( Darkness Ver.)",
	"Kono Subarashii Sekai ni Shukufuku wo! - ED ( Megumin Ver.)",
	"Kono Subarashii Sekai ni Shukufuku wo! - ED",
	"Kono Subarashii Sekai ni Shukufuku wo! - OP",
	"Kono Subarashii Sekai ni Shukufuku wo! 2  - ED ( Aqua Ver.)",
	"Kono Subarashii Sekai ni Shukufuku wo! 2  - ED ( Darkness Ver.)",
	"Kono Subarashii Sekai ni Shukufuku wo! 2  - ED ( Megumin Ver.)",
	"Kono Subarashii Sekai ni Shukufuku wo! 2  - ED",
	"Kono Subarashii Sekai ni Shukufuku wo! 2  - OP",
	"Koutetsujou no Kabaneri - ED",
	"Koutetsujou no Kabaneri - OP",
	"Kumo Desu ga, Nani ka - ED",
	"Kumo Desu ga, Nani ka - OP",
	"Kuroko no Basket - ED 01",
	"Kuroko no Basket - ED 02",
	"Kuroko no Basket - OP 01",
	"Kuroko no Basket - OP 02",
	"Kuroko no Basket 2nd Season - ED 01",
	"Kuroko no Basket 2nd Season - ED 02",
	"Kuroko no Basket 2nd Season - OP 01",
	"Kuroko no Basket 2nd Season - OP 02",
	"Kuroko no Basket 3rd Season - ED 01",
	"Kuroko no Basket 3rd Season - ED 02",
	"Kuroko no Basket 3rd Season - ED 03",
	"Kuroko no Basket 3rd Season - OP 01",
	"Kuroko no Basket 3rd Season - OP 02",
	"Kuroko no Basket 3rd Season - OP 03",
	"Kuroshitsuji - OP",
	"Kyoukai no Kanata - ED",
	"Kyoukai no Kanata - OP",
	"Kyoukai no Kanata - OST",
	"Little Witch Academia - ED 01",
	"Little Witch Academia - ED 02",
	"Little Witch Academia - OP 01",
	"Little Witch Academia - OP 02",
	"Log Horizon - ED",
	"Log Horizon - OP",
	"Log Horizon 2nd Season - ED",
	"Log Horizon Entaku Houkai - ED",
	"Log Horizon Entaku Houkai - OP",
	"Made in Abyss - ED",
	"Made in Abyss - OP",
	"Mahoutsukai no Yome - ED 01",
	"Mahoutsukai no Yome - ED 02",
	"Mahoutsukai no Yome - OP 01",
	"Mahoutsukai no Yome - OP 02",
	"Majo no Tabitabi - ED",
	"Majo no Tabitabi - OP",
	"Maou Gakuin no Futekigousha Shijou Saikyou no Maou no Shiso, Tensei shite Shison-tachi no Gakkou e - ED",
	"Maou Gakuin no Futekigousha Shijou Saikyou no Maou no Shiso, Tensei shite Shison-tachi no Gakkou e - OP",
	"Masamune-kun no Revenge - ED",
	"Masamune-kun no Revenge - OP",
	"Mekakucity Actors - ED",
	"Mekakucity Actors - OP",
	"Mieruko-chan - ED",
	"Mieruko-chan - OP",
	"Mirai Nikki - ED 01",
	"Mirai Nikki - ED 02",
	"Mirai Nikki - OP 01",
	"Mirai Nikki - OP 02",
	"Mob Psycho 100 - AMV 01",
	"Mob Psycho 100 - ED",
	"Mob Psycho 100 - OP",
	"Mob Psycho 100 II - ED 01",
	"Mob Psycho 100 II - ED 02",
	"Mob Psycho 100 II - ED 03",
	"Mob Psycho 100 II - ED 04",
	"Mob Psycho 100 II - OP",
	"Monogatari Series Second Season - ED 01",
	"Monogatari Series Second Season - ED 02",
	"Monogatari Series Second Season - ED 03",
	"Monogatari Series Second Season - OP 01",
	"Monogatari Series Second Season - OP 02",
	"Monogatari Series Second Season - OP 03",
	"Monogatari Series Second Season - OP 04",
	"Monogatari Series Second Season - OP 05",
	"Monogatari Series Second Season - OP 06",
	"Monster Musume no Iru Nichijou - ED",
	"Monster Musume no Iru Nichijou - OP",
	"Musaigen no Phantom World - ED",
	"Musaigen no Phantom World - OP",
	"Mushoku Tensei Isekai Ittara Honki Dasu - ED",
	"Mushoku Tensei Isekai Ittara Honki Dasu - OP 01",
	"Mushoku Tensei Isekai Ittara Honki Dasu - OP 02",
	"Mushoku Tensei Isekai Ittara Honki Dasu Part 2 - ED",
	"Mushoku Tensei Isekai Ittara Honki Dasu Part 2 - OP 01",
	"Mushoku Tensei Isekai Ittara Honki Dasu Part 2 - OP 03",
	"Nagi no Asukara - ED 01",
	"Nagi no Asukara - ED 02",
	"Nagi no Asukara - ED 03",
	"Nagi no Asukara - OP 01",
	"Nagi no Asukara - OP 02",
	"Nakitai Watashi wa Neko wo Kaburu - ED",
	"Nanatsu no Taizai - ED 01",
	"Nanatsu no Taizai - ED 02",
	"Nanatsu no Taizai - OP 01",
	"Nanatsu no Taizai - OP 02",
	"Nanatsu no Taizai Fundo no Shinpan - ED",
	"Nanatsu no Taizai Fundo no Shinpan - OP",
	"Nanatsu no Taizai Imashime no Fukkatsu - ED 01",
	"Nanatsu no Taizai Imashime no Fukkatsu - ED 02",
	"Nanatsu no Taizai Imashime no Fukkatsu - OP 01",
	"Nanatsu no Taizai Imashime no Fukkatsu - OP 02",
	"Nanatsu no Taizai Kamigami no Gekirin - ED 01",
	"Nanatsu no Taizai Kamigami no Gekirin - ED 02",
	"Nanatsu no Taizai Kamigami no Gekirin - OP 01",
	"Nanatsu no Taizai Kamigami no Gekirin - OP 02",
	"Nanatsu no Taizai Seisen no Shirushi - ED",
	"Nanatsu no Taizai Seisen no Shirushi - OP",
	"Naruto - ED 01",
	"Naruto - ED 02",
	"Naruto - ED 03",
	"Naruto - ED 04",
	"Naruto - ED 05",
	"Naruto - ED 06",
	"Naruto - ED 07",
	"Naruto - ED 08",
	"Naruto - ED 09",
	"Naruto - OP 01",
	"Naruto - OP 02",
	"Naruto - OP 03",
	"Naruto - OP 04",
	"Naruto - OP 05",
	"Naruto - OP 06",
	"Naruto - OP 07",
	"Naruto - OP 08",
	"Naruto - OP 09",
	"Naruto Shippuden - ED 01",
	"Naruto Shippuden - ED 02",
	"Naruto Shippuden - ED 03",
	"Naruto Shippuden - ED 04",
	"Naruto Shippuden - ED 05",
	"Naruto Shippuden - ED 06",
	"Naruto Shippuden - ED 07",
	"Naruto Shippuden - ED 08",
	"Naruto Shippuden - ED 09",
	"Naruto Shippuden - ED 10",
	"Naruto Shippuden - ED 11",
	"Naruto Shippuden - ED 12",
	"Naruto Shippuden - ED 13",
	"Naruto Shippuden - ED 14",
	"Naruto Shippuden - ED 15",
	"Naruto Shippuden - ED 16",
	"Naruto Shippuden - ED 17",
	"Naruto Shippuden - ED 18",
	"Naruto Shippuden - ED 19",
	"Naruto Shippuden - ED 20",
	"Naruto Shippuden - ED 21",
	"Naruto Shippuden - ED 22",
	"Naruto Shippuden - ED 23",
	"Naruto Shippuden - ED 24",
	"Naruto Shippuden - ED 25",
	"Naruto Shippuden - ED 26",
	"Naruto Shippuden - ED 27",
	"Naruto Shippuden - ED 28",
	"Naruto Shippuden - ED 29",
	"Naruto Shippuden - ED 30",
	"Naruto Shippuden - ED 31",
	"Naruto Shippuden - ED 32",
	"Naruto Shippuden - ED 33",
	"Naruto Shippuden - ED 34",
	"Naruto Shippuden - ED 35",
	"Naruto Shippuden - ED 36",
	"Naruto Shippuden - ED 37",
	"Naruto Shippuden - ED 38",
	"Naruto Shippuden - ED 39",
	"Naruto Shippuden - ED 40",
	"Naruto Shippuden - OP 01",
	"Naruto Shippuden - OP 02",
	"Naruto Shippuden - OP 03",
	"Naruto Shippuden - OP 04",
	"Naruto Shippuden - OP 05",
	"Naruto Shippuden - OP 06",
	"Naruto Shippuden - OP 07",
	"Naruto Shippuden - OP 08",
	"Naruto Shippuden - OP 09",
	"Naruto Shippuden - OP 10",
	"Naruto Shippuden - OP 11",
	"Naruto Shippuden - OP 12",
	"Naruto Shippuden - OP 13",
	"Naruto Shippuden - OP 14",
	"Naruto Shippuden - OP 15",
	"Naruto Shippuden - OP 16",
	"Naruto Shippuden - OP 17",
	"Naruto Shippuden - OP 18",
	"Naruto Shippuden - OP 19",
	"Naruto Shippuden - OP 20",
	"Nazo no Kanojo X - ED",
	"Nazo no Kanojo X - OP",
	"Nekomonogatari Kuro - ED",
	"Nekomonogatari Kuro - OP",
	"Neon Genesis Evangelion - OP YT",
	"Neon Genesis Evangelion - OP",
	"Netoge no Yome wa Onnanoko ja Nai to Omotta - ED",
	"Netoge no Yome wa Onnanoko ja Nai to Omotta - OP",
	"New Game! - ED",
	"New Game! - OP",
	"New Game!! - ED",
	"New Game!! - OP",
	"Nisekoi - ED 01",
	"Nisekoi - ED 02",
	"Nisekoi - ED 03",
	"Nisekoi - ED 04",
	"Nisekoi - ED 05",
	"Nisekoi - ED 06",
	"Nisekoi - OP 01",
	"Nisekoi - OP 02",
	"Nisekoi 2 - ED 01",
	"Nisekoi 2 - ED 02",
	"Nisekoi 2 - ED 03",
	"Nisekoi 2 - ED 04",
	"Nisekoi 2 - ED 05",
	"Nisekoi 2 - ED 06",
	"Nisekoi 2 - ED 07",
	"Nisekoi 2 - OP 01",
	"Nisekoi 2 - OP 02",
	"Nisemonogatari - ED",
	"Nisemonogatari - OP 01",
	"Nisemonogatari - OP 02",
	"Nisemonogatari - OP 03",
	"No Game No Life - ED",
	"No Game No Life - OP 01",
	"No Game No Life - OP 02",
	"No Game No Life Zero - ED",
	"Noragami - ED",
	"Noragami - OP",
	"Noragami Aragoto - ED",
	"Noragami Aragoto - OP",
	"One Piece - AMV",
	"One Piece - ED 01",
	"One Piece - ED 02",
	"One Piece - ED 03",
	"One Piece - ED 04",
	"One Piece - ED 05",
	"One Piece - ED 06",
	"One Piece - ED 07",
	"One Piece - ED 08",
	"One Piece - ED 09",
	"One Piece - ED 10",
	"One Piece - ED 11",
	"One Piece - ED 12",
	"One Piece - ED 13",
	"One Piece - ED 14",
	"One Piece - ED 15",
	"One Piece - ED 16",
	"One Piece - ED 17",
	"One Piece - ED 18",
	"One Piece - OP 01",
	"One Piece - OP 02",
	"One Piece - OP 03",
	"One Piece - OP 04",
	"One Piece - OP 05",
	"One Piece - OP 06",
	"One Piece - OP 07",
	"One Piece - OP 08",
	"One Piece - OP 09",
	"One Piece - OP 10",
	"One Piece - OP 11",
	"One Piece - OP 12",
	"One Piece - OP 13",
	"One Piece - OP 14",
	"One Piece - OP 15",
	"One Piece - OP 16",
	"One Piece - OP 17",
	"One Piece - OP 18",
	"One Piece - OP 19",
	"One Piece - OP 20",
	"One Piece - OP 21",
	"One Piece - OP 22",
	"One Piece - OP 23",
	"One Piece - OP 24",
	"One Punch Man - ED",
	"One Punch Man - OP",
	"One Punch Man 2nd Season - ED",
	"One Punch Man 2nd Season - OP",
	"Ookami to Koushinryou - ED",
	"Ookami to Koushinryou - OP",
	"Ookami to Koushinryou II - ED",
	"Ookami to Koushinryou II - OP",
	"Ore no Nounai Sentakushi ga, Gakuen Love Comedy wo Zenryoku de Jama Shiteiru - ED",
	"Ore no Nounai Sentakushi ga, Gakuen Love Comedy wo Zenryoku de Jama Shiteiru - OP",
	"Ousama Ranking - ED 01",
	"Ousama Ranking - ED 02",
	"Ousama Ranking - OP 01",
	"Ousama Ranking - OP 02",
	"Overlord - ED",
	"Overlord - OP",
	"Overlord II  - ED",
	"Overlord II  - OP",
	"Overlord III - ED",
	"Overlord III - OP",
	"Owari no Seraph - ED",
	"Owari no Seraph - OP",
	"Owari no Seraph Nagoya Kessen-hen - ED",
	"Owari no Seraph Nagoya Kessen-hen - OP",
	"Owarimonogatari - ED",
	"Owarimonogatari - OP 01",
	"Owarimonogatari - OP 02",
	"Owarimonogatari - OP 03",
	"Owarimonogatari - OP 04",
	"Owarimonogatari 2nd Season - ED",
	"Owarimonogatari 2nd Season - OP",
	"Pandora Hearts - ED 01",
	"Pandora Hearts - ED 02",
	"Pandora Hearts - OP",
	"Plastic Memories - ED",
	"Plastic Memories - OP",
	"Platinum End - ED",
	"Platinum End - OP",
	"Prison School - OP",
	"Psycho-Pass - ED 01",
	"Psycho-Pass - ED 02",
	"Psycho-Pass - OP 01",
	"Psycho-Pass - OP 02",
	"Psycho-Pass 2 - ED",
	"Psycho-Pass 2 - OP",
	"Psycho-Pass 3 - ED",
	"Psycho-Pass 3 - OP",
	"Rakudai Kishi no Cavalry - ED",
	"Rakudai Kishi no Cavalry - OP",
	"Re Zero kara Hajimeru Isekai Seikatsu - ED 01",
	"Re Zero kara Hajimeru Isekai Seikatsu - ED 02",
	"Re Zero kara Hajimeru Isekai Seikatsu - ED 03",
	"Re Zero kara Hajimeru Isekai Seikatsu - IS EP 14",
	"Re Zero kara Hajimeru Isekai Seikatsu - IS EP 15",
	"Re Zero kara Hajimeru Isekai Seikatsu - IS EP 7",
	"Re Zero kara Hajimeru Isekai Seikatsu - IS EP 8",
	"Re Zero kara Hajimeru Isekai Seikatsu - OP 01",
	"Re Zero kara Hajimeru Isekai Seikatsu - OP 02",
	"Re Zero kara Hajimeru Isekai Seikatsu 2nd Season - ED",
	"Re Zero kara Hajimeru Isekai Seikatsu 2nd Season - OP",
	"Re Zero kara Hajimeru Isekai Seikatsu 2nd Season Part 2 - ED",
	"Re Zero kara Hajimeru Isekai Seikatsu 2nd Season Part 2 - OP",
	"Rewrite - OP",
	"Rokudenashi Majutsu Koushi to Akashic Records - ED",
	"Rokudenashi Majutsu Koushi to Akashic Records - OP",
	"Saenai Heroine no Sodatekata - ED",
	"Saenai Heroine no Sodatekata - OP",
	"Saenai Heroine no Sodatekata ♭ - ED 01",
	"Saenai Heroine no Sodatekata ♭ - ED 02",
	"Saenai Heroine no Sodatekata ♭ - OP",
	"Sakamoto desu ga - ED",
	"Sakamoto desu ga - OP",
	"Sakurasou no Pet na Kanojo - ED 01",
	"Sakurasou no Pet na Kanojo - ED 02",
	"Sakurasou no Pet na Kanojo - OP 01",
	"Sakurasou no Pet na Kanojo - OP 02",
	"Sakurasou no Pet na Kanojo - OP 03",
	"Sankarea - ED",
	"Sankarea - OP",
	"Satsuriku no Tenshi - ED",
	"Satsuriku no Tenshi - OP",
	"Seiren - ED 01",
	"Seiren - ED 02",
	"Seiren - ED 03",
	"Seiren - OP",
	"Seishun Buta Yarou wa Bunny Girl Senpai no Yume wo Minai - ED (Mai Ver.)",
	"Seishun Buta Yarou wa Bunny Girl Senpai no Yume wo Minai - ED",
	"Seishun Buta Yarou wa Bunny Girl Senpai no Yume wo Minai - OP",
	"Sekai Saikou no Ansatsusha, Isekai Kizoku ni Tensei suru - ED",
	"Sekai Saikou no Ansatsusha, Isekai Kizoku ni Tensei suru - OP",
	"Senpai ga Uzai Kouhai no Hanashi - ED",
	"Senpai ga Uzai Kouhai no Hanashi - OP",
	"Shelter",
	"Shigatsu wa Kimi no Uso - ED 01",
	"Shigatsu wa Kimi no Uso - ED 02",
	"Shigatsu wa Kimi no Uso - OP 01",
	"Shigatsu wa Kimi no Uso - OP 02",
	"Shikioriori - ED",
	"Shimoneta to Iu Gainen ga Sonzai Shinai - ED",
	"Shimoneta to Iu Gainen ga Sonzai Shinai - OP",
	"Shingeki no Bahamut Genesis - ED",
	"Shingeki no Bahamut Genesis - OP",
	"Shingeki no Bahamut Virgin Soul - ED",
	"Shingeki no Bahamut Virgin Soul - OP",
	"Shingeki no Kyojin - ED 01",
	"Shingeki no Kyojin - ED 02",
	"Shingeki no Kyojin - OP 01",
	"Shingeki no Kyojin - OP 02",
	"Shingeki no Kyojin - Original Soundtrack 「Complete Album」",
	"Shingeki no Kyojin Lost Girls - ED",
	"Shingeki no Kyojin Season 2 - ED",
	"Shingeki no Kyojin Season 2 - OP",
	"Shingeki no Kyojin Season 2 - OST 05",
	"Shingeki no Kyojin Season 2 - Original Soundtrack 「Complete Album」",
	"Shingeki no Kyojin Season 3 - ED",
	"Shingeki no Kyojin Season 3 - OP",
	"Shingeki no Kyojin Season 3 - Original Soundtrack 「Complete Album」",
	"Shingeki no Kyojin Season 3 Part 2 - ED",
	"Shingeki no Kyojin Season 3 Part 2 - OP",
	"Shingeki no Kyojin Season 3 Part 2 - OST",
	"Shingeki no Kyojin The Final Season - ED",
	"Shingeki no Kyojin The Final Season - OP",
	"Shingeki no Kyojin The Final Season - OST",
	"Shingeki no Kyojin The Final Season Part 2 - ED",
	"Shingeki no Kyojin The Final Season Part 2 - OP",
	"Shingeki! Kyojin Chuugakkou - ED",
	"Shingeki! Kyojin Chuugakkou - IS",
	"Shingeki! Kyojin Chuugakkou - OP",
	"Shokugeki no Souma - ED 01",
	"Shokugeki no Souma - ED 02",
	"Shokugeki no Souma - OP 01",
	"Shokugeki no Souma - OP 02",
	"Shokugeki no Souma Gou no Sara - ED",
	"Shokugeki no Souma Gou no Sara - OP",
	"Shokugeki no Souma Ni no Sara - ED",
	"Shokugeki no Souma Ni no Sara - OP",
	"Shokugeki no Souma San no Sara - ED",
	"Shokugeki no Souma San no Sara - OP",
	"Shokugeki no Souma San no Sara - Toutsuki Ressha-hen - ED",
	"Shokugeki no Souma San no Sara - Toutsuki Ressha-hen - OP",
	"Shokugeki no Souma Shin no Sara - OP",
	"Sono Bisque Doll wa Koi wo Suru - ED",
	"Sono Bisque Doll wa Koi wo Suru - OP",
	"Sora yori mo Tooi Basho - ED",
	"Sora yori mo Tooi Basho - IS 01",
	"Sora yori mo Tooi Basho - IS 02",
	"Sora yori mo Tooi Basho - OP",
	"Soul Eater - OP 01",
	"Soul Eater - OP 02",
	"Sousei no Onmyouji - ED 01",
	"Sousei no Onmyouji - ED 02",
	"Sousei no Onmyouji - ED 04",
	"Sousei no Onmyouji - ED 05",
	"Sousei no Onmyouji - OP 01",
	"Sousei no Onmyouji - OP 02",
	"Sousei no Onmyouji - OP 03",
	"Sousei no Onmyouji - OP 04",
	"Steins;Gate - ED 01",
	"Steins;Gate - ED 02",
	"Steins;Gate - ED 03",
	"Steins;Gate - ED 04",
	"Steins;Gate - OP",
	"Steins;Gate 0 - ED 01",
	"Steins;Gate 0 - ED 02",
	"Steins;Gate 0 - OP",
	"Steins;Gate 0 - OST 01",
	"Sword Art Online - ED 01",
	"Sword Art Online - ED 02",
	"Sword Art Online - OP 01",
	"Sword Art Online - OP 02",
	"Sword Art Online Alicization - ED 01",
	"Sword Art Online Alicization - ED 02",
	"Sword Art Online Alicization - IS 01",
	"Sword Art Online Alicization - OP 01",
	"Sword Art Online Alicization - OP 02",
	"Sword Art Online Alicization - War of Underworld 2nd Season - ED",
	"Sword Art Online Alicization - War of Underworld 2nd Season - OP",
	"Sword Art Online Alicization War of Underworld - ED",
	"Sword Art Online Alicization War of Underworld - OP",
	"Sword Art Online Alternative Gun Gale Online - ED",
	"Sword Art Online Alternative Gun Gale Online - OP",
	"Sword Art Online Alternative Gun Gale Online - OST 01",
	"Sword Art Online Alternative Gun Gale Online - OST 02",
	"Sword Art Online II - ED 01",
	"Sword Art Online II - ED 02",
	"Sword Art Online II - ED 03",
	"Sword Art Online II - OP 01",
	"Sword Art Online II - OP 02",
	"Sword Art Online Ordinal Scale - OST",
	"Sword Art Online Progressive Movie - Hoshi Naki Yoru no Aria - OP",
	"Takt Op. Destiny - ED",
	"Takt Op. Destiny - OP",
	"Tales of Zestiria the X - OP",
	"Tate no Yuusha no Nariagari - ED 01",
	"Tate no Yuusha no Nariagari - ED 02",
	"Tate no Yuusha no Nariagari - OP 01",
	"Tate no Yuusha no Nariagari - OP 02",
	"Tejina-senpai - ED",
	"Tejina-senpai - OP",
	"Tenki no Ko - OST 06",
	"Tenki no Ko - OST 12",
	"Tenki no Ko - OST 27",
	"Tenki no Ko - OST 28",
	"Tenki no Ko - OST 29",
	"Tenki no Ko - OST 30",
	"Tenki no Ko - OST 31",
	"Tensei shitara Slime Datta Ken - ED 01",
	"Tensei shitara Slime Datta Ken - ED 02",
	"Tensei shitara Slime Datta Ken - OP 01",
	"Tensei shitara Slime Datta Ken - OP 02",
	"Tensei shitara Slime Datta Ken 2nd Season - ED 02",
	"Tensei shitara Slime Datta Ken 2nd Season - ED",
	"Tensei shitara Slime Datta Ken 2nd Season - OP",
	"Tensei shitara Slime Datta Ken 2nd Season Part 2 - OP",
	"The God of High School - ED",
	"The God of High School - OP",
	"Tokyo Ghoul - ED",
	"Tokyo Ghoul - OP",
	"Tokyo Ghoul re - ED",
	"Tokyo Ghoul re - OP",
	"Tokyo Ghoul re 2nd Season - ED",
	"Tokyo Ghoul re 2nd Season - OP",
	"Tokyo Ghoul √A - ED",
	"Tokyo Ghoul √A - OP",
	"Tokyo Ghoul √A - OST 01",
	"Tokyo Ghoul √A - OST 02",
	"Tokyo Ghoul √A - OST 04",
	"Tokyo Ghoul √A - OST 33",
	"Tokyo Revengers - OP",
	"Tonikaku Kawaii - ED",
	"Tonikaku Kawaii - OP",
	"Toradora! - ED 01",
	"Toradora! - ED 02",
	"Toradora! - ED 03",
	"Toradora! - OP 01",
	"Toradora! - OP 02",
	"Tsuki ga Michibiku Isekai Douchuu - OP",
	"Tsuki to Laika to Nosferatu - ED",
	"Tsuki to Laika to Nosferatu - OP",
	"Tsukimonogatari - ED",
	"Tsukimonogatari - OP",
	"Tsurezure Children - ED",
	"Tsurezure Children - OP",
	"Uchi no Maid ga Uzasugiru! - ED",
	"Uchi no Maid ga Uzasugiru! - OP",
	"Uchiage Hanabi Shita kara Miru ka Yoko kara Miru ka - ED",
	"Uma Musume Pretty Derby - ED 01",
	"Uma Musume Pretty Derby - ED 02",
	"Uma Musume Pretty Derby - OP",
	"Uma Musume Pretty Derby - OST",
	"Uzaki-chan wa Asobitai! - ED",
	"Uzaki-chan wa Asobitai! - OP",
	"Vanitas no Karte - ED",
	"Vanitas no Karte - OP",
	"Vanitas no Karte Part 2 - ED",
	"Vanitas no Karte Part 2 - OP",
	"Vinland Saga - ED 01",
	"Vinland Saga - ED 02",
	"Vinland Saga - OP 01",
	"Vinland Saga - OP 02",
	"Violet Evergarden - ED",
	"Violet Evergarden - OP",
	"Watashi ga Motenai no wa Dou Kangaetemo Omaera ga Warui! - OP",
	"Wonder Egg Priority - ED",
	"Wonder Egg Priority - OP",
	"Wotaku ni Koi wa Muzukashii - ED",
	"Wotaku ni Koi wa Muzukashii - OP",
	"YOASOBI - Gunjou",
	"YOASOBI - Yoru Ni Kakeru",
	"Yahari Ore no Seishun Love Comedy wa Machigatteiru. - ED 01",
	"Yahari Ore no Seishun Love Comedy wa Machigatteiru. - ED 02",
	"Yahari Ore no Seishun Love Comedy wa Machigatteiru. - ED 03",
	"Yahari Ore no Seishun Love Comedy wa Machigatteiru. - ED 04",
	"Yahari Ore no Seishun Love Comedy wa Machigatteiru. - OP",
	"Yahari Ore no Seishun Love Comedy wa Machigatteiru. Kan - ED 01",
	"Yahari Ore no Seishun Love Comedy wa Machigatteiru. Kan - ED 02",
	"Yahari Ore no Seishun Love Comedy wa Machigatteiru. Kan - ED 03",
	"Yahari Ore no Seishun Love Comedy wa Machigatteiru. Kan - OP",
	"Yahari Ore no Seishun Love Comedy wa Machigatteiru. Zoku - ED 01",
	"Yahari Ore no Seishun Love Comedy wa Machigatteiru. Zoku - ED 02",
	"Yahari Ore no Seishun Love Comedy wa Machigatteiru. Zoku - ED 03",
	"Yahari Ore no Seishun Love Comedy wa Machigatteiru. Zoku - IS",
	"Yahari Ore no Seishun Love Comedy wa Machigatteiru. Zoku - OP",
	"Yakusoku no Neverland - ED 02",
	"Yakusoku no Neverland - ED",
	"Yakusoku no Neverland - OP",
	"Yakusoku no Neverland 2nd Season - ED",
	"Yakusoku no Neverland 2nd Season - OP",
	"Yamada-kun to 7-nin no Majo - ED",
	"Yamada-kun to 7-nin no Majo - OP",
	"Youjo Senki - ED 01",
	"Youjo Senki - ED 02",
	"Youjo Senki - OP",
	"Youjo Senki Movie - IS",
	"Yuru Camp△ - ED",
	"Yuru Camp△ - OP",
	"Yuru Camp△ Heya Camp△ - ED",
	"Yuru Camp△ Season 2 - ED",
	"Yuru Camp△ Season 2 - OP",
	"Zankyou no Terror - ED",
	"Zankyou no Terror - OP",
	"Zero kara Hajimeru Mahou no Sho - ED",
	"Zero kara Hajimeru Mahou no Sho - OP",
	"Zoku Owarimonogatari - OP",
	"Zoku Owarimonogatari - OST",
	"Zombieland Saga - ED",
	"Zombieland Saga - OP",
	"Zombieland Saga Revenge - ED",
	"Zombieland Saga Revenge - OP"
]